version: '3.7'
services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mhy
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mhy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
    networks:
      - mhy
    ports:
      - '14268:14268'
      - '6832:6832/udp'
      - '3200:3200'

  loki:
    image: grafana/loki:2.4.2
    ports:
      - '3100:3100'
    volumes:
      - ./config/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - mhy
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:8.3.4
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - mhy
    ports:
      - '3000:3000'
networks:
  mhy:
    name: mhy
